export const GET_DEVICES_REQUEST = `GET_DEVICES_REQUEST`;
export const GET_DEVICES_SUCCESS = `GET_DEVICES_SUCCESS`;
export const GET_DEVICES_FAILURE = `GET_DEVICES_FAILURE`;

export const REMOVE_DEVICE_REQUEST = `REMOVE_DEVICE_REQUEST`;
export const REMOVE_DEVICE_SUCCESS = `REMOVE_DEVICE_SUCCESS`;
export const REMOVE_DEVICE_FAILURE = `REMOVE_DEVICE_FAILURE`;

export const GET_DEVICE_REQUEST = `GET_DEVICE_REQUEST`;
export const GET_DEVICE_SUCCESS = `GET_DEVICE_SUCCESS`;
export const GET_DEVICE_FAILURE = `GET_DEVICE_FAILURE`;

export const SAVE_DEVICE_REQUEST = `SAVE_DEVICE_REQUEST`;
export const SAVE_DEVICE_SUCCESS = `SAVE_DEVICE_SUCCESS`;
export const SAVE_DEVICE_FAILURE = `SAVE_DEVICE_FAILURE`;

export const SET_DEVICE = `SET_DEVICE`;
export const REMOVE_DEVICE = `REMOVE_DEVICE`;