export const GET_NETWORKS_REQUEST = `GET_NETWORKS_REQUEST`;
export const GET_NETWORKS_SUCCESS = `GET_NETWORKS_SUCCESS`;
export const GET_NETWORKS_FAILURE = `GET_NETWORKS_FAILURE`;

export const CREATE_NETWORK_REQUEST = `CREATE_NETWORK_REQUEST`;
export const CREATE_NETWORK_SUCCESS = `CREATE_NETWORK_SUCCESS`;
export const CREATE_NETWORK_FAILURE = `CREATE_NETWORK_FAILURE`;

export const UPDATE_NETWORK_REQUEST = `UPDATE_NETWORK_REQUEST`;
export const UPDATE_NETWORK_SUCCESS = `UPDATE_NETWORK_SUCCESS`;
export const UPDATE_NETWORK_FAILURE = `UPDATE_NETWORK_FAILURE`;

export const REMOVE_NETWORK_REQUEST = `REMOVE_NETWORK_REQUEST`;
export const REMOVE_NETWORK_SUCCESS = `REMOVE_NETWORK_SUCCESS`;
export const REMOVE_NETWORK_FAILURE = `REMOVE_NETWORK_FAILURE`;