export const GET_DEVICE_NOTIFICATION_POLL_REQUEST = `GET_DEVICE_NOTIFICATION_POLL_REQUEST`;
export const GET_DEVICE_NOTIFICATION_POLL_SUCCESS = `GET_DEVICE_NOTIFICATION_POLL_SUCCESS`;
export const GET_DEVICE_NOTIFICATION_POLL_FAILURE = `GET_DEVICE_NOTIFICATION_POLL_FAILURE`;

export const GET_DEVICE_COMMAND_POLL_REQUEST = `GET_DEVICE_COMMAND_POLL_REQUEST`;
export const GET_DEVICE_COMMAND_POLL_SUCCESS = `GET_DEVICE_COMMAND_POLL_SUCCESS`;
export const GET_DEVICE_COMMAND_POLL_FAILURE = `GET_DEVICE_COMMAND_POLL_FAILURE`;

export const UPDATE_TAB = `UPDATE_TAB`;

export const GET_DEVICE_COMMAND_POLL_HISTORY_REQUEST = `GET_DEVICE_COMMAND_POLL_HISTORY_REQUEST`;
export const GET_DEVICE_COMMAND_POLL_HISTORY_SUCCESS = `GET_DEVICE_COMMAND_POLL_HISTORY_SUCCESS`;
export const GET_DEVICE_COMMAND_POLL_HISTORY_FAILURE = `GET_DEVICE_COMMAND_POLL_HISTORY_FAILURE`;

export const GET_DEVICE_NOTIFICATION_POLL_HISTORY_REQUEST = `GET_DEVICE_NOTIFICATION_POLL_HISTORY_REQUEST`;
export const GET_DEVICE_NOTIFICATION_POLL_HISTORY_SUCCESS = `GET_DEVICE_NOTIFICATION_POLL_HISTORY_SUCCESS`;
export const GET_DEVICE_NOTIFICATION_POLL_HISTORY_FAILURE = `GET_DEVICE_NOTIFICATION_POLL_HISTORY_FAILURE`;

export const SET_DEVICE = `SET_DEVICE`;
export const REMOVE_DEVICE = `REMOVE_DEVICE`;

export const SET_TIME_PERIOD = `SET_TIME_PERIOD`;

export const GET_DEVICE_COMMAND_POLL_PERIOD_REQUEST = `GET_DEVICE_COMMAND_POLL_PERIOD_REQUEST`;
export const GET_DEVICE_COMMAND_POLL_PERIOD_SUCCESS = `GET_DEVICE_COMMAND_POLL_PERIOD_SUCCESS`;
export const GET_DEVICE_COMMAND_POLL_PERIOD_FAILURE = `GET_DEVICE_COMMAND_POLL_PERIOD_FAILURE`;

export const GET_DEVICE_NOTIFICATION_POLL_PERIOD_REQUEST = `GET_DEVICE_NOTIFICATION_POLL_PERIOD_REQUEST`;
export const GET_DEVICE_NOTIFICATION_POLL_PERIOD_SUCCESS = `GET_DEVICE_NOTIFICATION_POLL_PERIOD_SUCCESS`;
export const GET_DEVICE_NOTIFICATION_POLL_PERIOD_FAILURE = `GET_DEVICE_NOTIFICATION_POLL_PERIOD_FAILURE`;