export const GET_DEVICE_NOTIFICATION_POLL_REQUEST = `GET_DEVICE_NOTIFICATION_POLL_REQUEST`;
export const GET_DEVICE_NOTIFICATION_POLL_SUCCESS = `GET_DEVICE_NOTIFICATION_POLL_SUCCESS`;
export const GET_DEVICE_NOTIFICATION_POLL_FAILURE = `GET_DEVICE_NOTIFICATION_POLL_FAILURE`;

export const GET_DEVICE_COMMAND_POLL_REQUEST = `GET_DEVICE_COMMAND_POLL_REQUEST`;
export const GET_DEVICE_COMMAND_POLL_SUCCESS = `GET_DEVICE_COMMAND_POLL_SUCCESS`;
export const GET_DEVICE_COMMAND_POLL_FAILURE = `GET_DEVICE_COMMAND_POLL_FAILURE`;

export const UPDATE_TAB = `UPDATE_TAB`;