export const GET_USERS_REQUEST = `GET_USERS_REQUEST`;
export const GET_USERS_SUCCESS = `GET_USERS_SUCCESS`;
export const GET_USERS_FAILURE = `GET_USERS_FAILURE`;

export const CREATE_USER_REQUEST = `CREATE_USER_REQUEST`;
export const CREATE_USER_SUCCESS = `CREATE_USER_SUCCESS`;
export const CREATE_USER_FAILURE = `CREATE_USER_FAILURE`;

export const REMOVE_USER_REQUEST = `REMOVE_USER_REQUEST`;
export const REMOVE_USER_SUCCESS = `REMOVE_USER_SUCCESS`;
export const REMOVE_USER_FAILURE = `REMOVE_USER_FAILURE`;

export const GET_USER_REQUEST = `GET_USER_REQUEST`;
export const GET_USER_SUCCESS = `GET_USER_SUCCESS`;
export const GET_USER_FAILURE = `GET_USER_FAILURE`;

export const SAVE_USER_REQUEST = `SAVE_USER_REQUEST`;
export const SAVE_USER_SUCCESS = `SAVE_USER_SUCCESS`;
export const SAVE_USER_FAILURE = `SAVE_USER_FAILURE`;

export const ASSIGN_NETWORK_REQUEST = `ASSIGN_NETWORK_REQUEST`;
export const ASSIGN_NETWORK_SUCCESS = `ASSIGN_NETWORK_SUCCESS`;
export const ASSIGN_NETWORK_FAILURE = `ASSIGN_NETWORK_FAILURE`;

export const UNASSIGN_NETWORK_REQUEST = `UNASSIGN_NETWORK_REQUEST`;
export const UNASSIGN_NETWORK_SUCCESS = `UNASSIGN_NETWORK_SUCCESS`;
export const UNASSIGN_NETWORK_FAILURE = `UNASSIGN_NETWORK_FAILURE`;